openapi: 3.1.0
info:
  version: 1.0.0
  title: Students app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Tasteorama app
tags:
  - name: Auth
    description: Auth operations.
  - name: Users
    description: Operations about users.
  - name: Categories
    description: Operations about categories.
  - name: Ingredients
    description: Operations about ingredients.
  - name: Recipes
    description: Operations about recipes.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
